sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t familyman80/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true familyman80/docker-react npm run test -- --coverage

after_success:
  - echo "Test Success"
