sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t familyman80/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true familyman80/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerreactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-415864962319"
  bucket_path: "docker-react-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY;
  secret_access_key: $AWS_SECRET_KEY

after_success:
  - echo "Test Success"
