#베이스 이미지 명시
FROM node:alpine

WORKDIR "/usr/src/app"

#package.json 내용이 안바뀌면 npm install 이 안돌도록 
COPY package.json ./

#추가적으로 필요한 파일들을 다운로드
RUN npm install

#package.json 카피하기
COPY ./ ./

#컨테이너 시작시 실행될 명령어 명시
CMD ["npm", "run", "start"]